services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - '9090:9090'
    networks:
      - monitoring_network

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./prometheus:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yaml'
    ports:
      - '9093:9093'
    networks:
      - monitoring_network        
        
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3333:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring_network

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - '9100:9100'
    networks:
      - monitoring_network

  nginx_exporter_backend:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx-exporter-backend
    command:
      - '--nginx.scrape-uri=http://65.2.168.175:81/metrics'
    ports:
      - '9113:9113'
    networks:
      - monitoring_network

  nginx_exporter_frontend:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx-exporter-frontend
    command:
      - '--nginx.scrape-uri=http://65.2.168.175:82/metrics'
    ports:
      - '9114:9113'
    networks:
      - monitoring_network
 
volumes:
  grafana-storage:

networks:
  monitoring_network:
