global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'itsmeashikmak@gmail.com'
  smtp_auth_username: 'itsmeashikmak@gmail.com'
  smtp_auth_password: 'jwhe mjul rhsk olhg'
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1m
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - to: 'itsmeashikmak@gmail.com'
        send_resolved: true

